import http from 'node:http';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {WebSocketServer,WebSocket} from 'ws';
import {CITIES_1300,CITY_1300} from '../src/data1300.js';
import {MILITARY_UNIT_1300,startingComposition1300} from '../src/military1300.js';
import {BUILDINGS_1300,BUILDING_1300,buildingCost1300,startingBuildingLevel1300,isCoastalCity1300} from '../src/buildings1300.js';
import {ensurePvPRuntime,processPvPDay,startPvPMovement,handlePvPCommand} from './pvp1300.js';
import {ensureMultiplayerEconomy1300,processMultiplayerEconomyWeek1300,handleEconomyCommand1300} from './multiplayer-economy1300.js';

const PORT=Number(process.env.PORT)||8787,MAX_PLAYERS=6,RECONNECT_GRACE_MS=45000,WAITING_TTL_MS=6*60*60*1000,CAMPAIGN_TTL_MS=7*24*60*60*1000;
const PREPARATION_MS=120000,DAY_MS=2000;
const __dirname=path.dirname(fileURLToPath(import.meta.url)),SAVE_FILE=process.env.CARDWARS_MULTIPLAYER_SAVE||path.join(__dirname,'data','multiplayer-state.json');
const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const cleanName=v=>String(v||'Player').trim().replace(/[<>]/g,'').slice(0,28)||'Player';
const cleanColor=v=>/^#[0-9a-f]{6}$/i.test(String(v||''))?String(v):'#c6534d';
const cleanCode=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);
const cleanDeck=v=>Array.isArray(v)?[...new Set(v.map(x=>String(x)).filter(Boolean))].slice(0,16):[];
const send=(ws,payload)=>{if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify(payload));};
const shuffle=v=>{const a=[...v];for(let i=a.length-1;i>0;i--){const j=crypto.randomInt(i+1),t=a[i];a[i]=a[j];a[j]=t;}return a;};
const validDeck=p=>cleanDeck(p?.deck).filter(id=>!!CITY_1300[id]);
function allocateStartingHands(players){
 const entries=players.map(p=>({id:p.id,deck:validDeck(p)}));for(const row of entries)if(row.deck.length<4)throw new Error(row.id+' does not have four valid Cardwars cities in their deck.');
 const slots=shuffle(entries.flatMap(row=>Array.from({length:4},(_,slot)=>({playerId:row.id,slot,deck:shuffle(row.deck)})))),cityMatch=new Map();
 const visit=(slot,seen)=>{for(const cityId of slot.deck){if(seen.has(cityId))continue;seen.add(cityId);const previous=cityMatch.get(cityId);if(!previous||visit(previous,seen)){cityMatch.set(cityId,slot);return true;}}return false;};
 for(const slot of slots)if(!visit(slot,new Set()))throw new Error('These decks overlap too much to give every player 4 unique starting cities. Change at least one deck and try again.');
 const hands=Object.fromEntries(entries.map(row=>[row.id,[]]));for(const [cityId,slot] of cityMatch)hands[slot.playerId].push(cityId);for(const id of Object.keys(hands))hands[id]=shuffle(hands[id]).slice(0,4);return hands;
}
function campaignPlayerState(player,hand){
 const cities=hand.map(id=>CITY_1300[id]).filter(Boolean),startingFlorins=Math.round(cities.reduce((n,c)=>n+(Number(c.startingFlorins)||.01),0)*100)/100,armyByCity=Object.fromEntries(cities.map(c=>[c.id,{army:Math.max(0,Math.round(Number(c.army)||0)),navy:Math.max(0,Math.round(Number(c.navy)||0))}]));
 return {id:player.id,name:player.name,color:player.color,flag:player.flag||[],deck:[...player.deck],hand:[...hand],ownedCities:[...hand],realmName:player.name+"'s Rebellion",campaignStage:'rebellion',startingFlorins,florins:startingFlorins,armyByCity,originCountryByCity:Object.fromEntries(cities.map(c=>[c.id,c.country])),trainingQueues:[],movements:[],construction:[],buildings:{},trainedUnitsByCity:{},nextTrainingId:1,nextMovementId:1,nextConstructionId:1,events:[],createdAt:Date.now()};
}
function initializeCampaignOwnership(players){
 const hands=allocateStartingHands(players),playerStates={},cityOwners={};for(const p of players){const state=campaignPlayerState(p,hands[p.id]);playerStates[p.id]=state;for(const id of state.ownedCities)cityOwners[id]=p.id;}return {playerStates,cityOwners};
}
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0)),round2=n=>Math.round((Number(n)||0)*100)/100;
function ensureCampaignPlayerRuntime(campaign,state){
 if(!state)return null;state.armyByCity=state.armyByCity&&typeof state.armyByCity==='object'?state.armyByCity:{};state.trainingQueues=Array.isArray(state.trainingQueues)?state.trainingQueues:[];state.movements=Array.isArray(state.movements)?state.movements:[];state.construction=Array.isArray(state.construction)?state.construction:[];state.buildings=state.buildings&&typeof state.buildings==='object'&&!Array.isArray(state.buildings)?state.buildings:{};state.trainedUnitsByCity=state.trainedUnitsByCity&&typeof state.trainedUnitsByCity==='object'&&!Array.isArray(state.trainedUnitsByCity)?state.trainedUnitsByCity:{};state.nextTrainingId=Math.max(1,Math.floor(Number(state.nextTrainingId)||1));state.nextMovementId=Math.max(1,Math.floor(Number(state.nextMovementId)||1));state.nextConstructionId=Math.max(1,Math.floor(Number(state.nextConstructionId)||1));
 for(const cityId of state.ownedCities||[]){const c=CITY_1300[cityId];if(!c)continue;state.armyByCity[cityId]??={army:Math.max(0,Math.round(Number(c.army)||0)),navy:Math.max(0,Math.round(Number(c.navy)||0))};state.armyByCity[cityId].army=Math.max(0,Math.floor(Number(state.armyByCity[cityId].army)||0));state.armyByCity[cityId].navy=Math.max(0,Math.floor(Number(state.armyByCity[cityId].navy)||0));state.buildings[cityId]??={};if(!state.trainedUnitsByCity[cityId])state.trainedUnitsByCity[cityId]=startingComposition1300(state.armyByCity[cityId].army,Number(c.technology)||50);}
 return state;
}
function ensureCampaignRuntime(campaign){if(!campaign)return null;campaign.playerStates??={};campaign.cityOwners??={};for(const state of Object.values(campaign.playerStates))ensureCampaignPlayerRuntime(campaign,state);ensurePvPRuntime(campaign);ensureMultiplayerEconomy1300(campaign);return campaign;}
function playerArmyTotal(state){return Object.values(state?.armyByCity||{}).reduce((n,row)=>n+Math.max(0,Number(row?.army)||0),0)+(state?.movements||[]).reduce((n,m)=>n+Math.max(0,Number(m?.count)||0),0)+Object.values(state?.fieldArmies||{}).reduce((n,row)=>n+Math.max(0,Number(row?.count)||0),0);}
function playerProfessionalCap(state){return Math.max(0,Math.floor((state?.ownedCities||[]).reduce((n,id)=>n+Math.max(0,Number(CITY_1300[id]?.people)||0),0)*.05));}
function pendingTrainingTotal(state){return (state?.trainingQueues||[]).reduce((n,q)=>n+Math.max(0,Number(q?.amount)||0),0);}
function haversineKm(a,b){const rad=x=>x*Math.PI/180,lat1=rad(Number(a?.lat)||0),lat2=rad(Number(b?.lat)||0),dLat=lat2-lat1,dLon=rad((Number(b?.lon)||0)-(Number(a?.lon)||0)),h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(Math.max(0,1-h)));}
function armyTravelDays(from,to){return Math.max(3,Math.min(10,Math.round(3+haversineKm(from,to)/300)));}
function multiplayerBuildingLevel(state,cityId,buildingId){return Math.max(0,startingBuildingLevel1300(CITY_1300[cityId],buildingId)+(Number(state?.buildings?.[cityId]?.[buildingId])||0));}
function multiplayerConstructionDays(building,level,cost){let days=14+((Math.max(50,Math.min(400,Number(cost)||50))-50)/350)*21+Math.max(0,Number(level)||0)*7;if(/defence|knowledge|navy|civic/.test(String(building?.category||'').toLowerCase()))days+=4;return Math.max(14,Math.min(56,Math.round(days/7)*7));}
function addPlayerEvent(state,text,day){state.events=Array.isArray(state.events)?state.events:[];state.events.unshift({day:Math.max(0,Math.floor(Number(day)||0)),text:String(text||'').slice(0,180)});state.events=state.events.slice(0,16);}
function processCampaignSystems(campaign){
 ensureCampaignRuntime(campaign);let changed=false;const day=Math.max(0,Math.floor(Number(campaign.day)||0));
 for(const state of Object.values(campaign.playerStates||{})){
  const doneTraining=state.trainingQueues.filter(q=>day>=Number(q.finishDay));if(doneTraining.length){for(const q of doneTraining){const row=state.armyByCity[q.cityId];if(!row)continue;row.army=Math.max(0,Number(row.army)||0)+q.amount;state.trainedUnitsByCity[q.cityId]??={};state.trainedUnitsByCity[q.cityId][q.unitId]=(Number(state.trainedUnitsByCity[q.cityId][q.unitId])||0)+q.amount;addPlayerEvent(state,q.amount+' '+(MILITARY_UNIT_1300[q.unitId]?.name||'soldiers')+' finished training in '+(CITY_1300[q.cityId]?.name||q.cityId)+'.',day);}state.trainingQueues=state.trainingQueues.filter(q=>day<Number(q.finishDay));changed=true;}
  const finished=state.construction.filter(j=>day>=Number(j.completeDay));if(finished.length){for(const j of finished){state.buildings[j.cityId]??={};state.buildings[j.cityId][j.buildingId]=(Number(state.buildings[j.cityId][j.buildingId])||0)+1;addPlayerEvent(state,(BUILDING_1300[j.buildingId]?.name||j.buildingId)+' reached level '+j.toLevel+' in '+(CITY_1300[j.cityId]?.name||j.cityId)+'.',day);}state.construction=state.construction.filter(j=>day<Number(j.completeDay));changed=true;}
 }
 if(processPvPDay(campaign,day))changed=true;if(processMultiplayerEconomyWeek1300(campaign,day))changed=true;return changed;
}

class LobbyStore{
 constructor(){this.lobbies=new Map();this.clientLobby=new Map();this.saveTimer=null;this.load();}
 code(){for(let tries=0;tries<1000;tries++){let out='';for(let i=0;i<6;i++)out+=alphabet[crypto.randomInt(alphabet.length)];if(!this.lobbies.has(out))return out;}throw new Error('Unable to allocate lobby code');}
 player(clientId,raw={}){const deck=cleanDeck(raw.deck);return {id:clientId,name:cleanName(raw.name),color:cleanColor(raw.color),deck,deckCount:Math.max(0,Math.min(16,Number(raw.deckCount)||deck.length)),flag:Array.isArray(raw.flag)?raw.flag.slice(0,36):[],ready:false,connected:true,joinedAt:Date.now()};}
 create(clientId,raw){this.leave(clientId,false);const code=this.code(),p=this.player(clientId,raw),lobby={code,hostId:clientId,status:'waiting',createdAt:Date.now(),updatedAt:Date.now(),players:new Map([[clientId,p]]),campaign:null};this.lobbies.set(code,lobby);this.clientLobby.set(clientId,code);this.scheduleSave();return lobby;}
 join(clientId,codeRaw,raw){const code=cleanCode(codeRaw),lobby=this.lobbies.get(code);if(!lobby)throw new Error('Lobby not found. Check the invite code.');if(lobby.status!=='waiting')throw new Error('This lobby has already started.');const existing=lobby.players.get(clientId),deck=cleanDeck(raw.deck);if(existing){Object.assign(existing,{name:cleanName(raw.name),color:cleanColor(raw.color),deck,deckCount:Math.max(0,Math.min(16,Number(raw.deckCount)||deck.length)),flag:Array.isArray(raw.flag)?raw.flag.slice(0,36):[],connected:true});this.clientLobby.set(clientId,code);this.touch(lobby);return lobby;}if(lobby.players.size>=MAX_PLAYERS)throw new Error('This lobby is full (6/6).');this.leave(clientId,false);lobby.players.set(clientId,this.player(clientId,raw));this.clientLobby.set(clientId,code);this.touch(lobby);return lobby;}
 resume(clientId,codeRaw,raw){const code=cleanCode(codeRaw),lobby=this.lobbies.get(code);if(!lobby)throw new Error('Saved multiplayer lobby no longer exists.');const p=lobby.players.get(clientId);if(!p)throw new Error('Your saved player slot no longer exists in this lobby.');Object.assign(p,{name:cleanName(raw?.name||p.name),color:cleanColor(raw?.color||p.color),connected:true});this.clientLobby.set(clientId,code);this.touch(lobby);return lobby;}
 setReady(clientId,ready){const lobby=this.forClient(clientId);if(!lobby)throw new Error('You are not in a lobby.');if(lobby.status!=='waiting')throw new Error('Campaign already started.');lobby.players.get(clientId).ready=!!ready;this.touch(lobby);return lobby;}
 start(clientId){const lobby=this.forClient(clientId);if(!lobby)throw new Error('You are not in a lobby.');if(lobby.hostId!==clientId)throw new Error('Only the host can start the lobby.');if(lobby.status!=='waiting')throw new Error('Lobby already started.');const players=[...lobby.players.values()];if(players.some(p=>!p.ready))throw new Error('Every player must be Ready before starting.');for(const p of players)if(validDeck(p).length!==16)throw new Error(p.name+' needs a valid 16-card deck before the campaign can start.');const ownership=initializeCampaignOwnership(players),now=Date.now();lobby.status='started';lobby.gameId=crypto.randomUUID();lobby.campaign={id:lobby.gameId,phase:'preparing',day:0,createdAt:now,startedAt:null,prepEndsAt:now+PREPARATION_MS,nextDayAt:null,dayDurationMs:DAY_MS,preparationMs:PREPARATION_MS,lastBroadcastSecond:null,playerStates:ownership.playerStates,cityOwners:ownership.cityOwners};this.touch(lobby,true);return lobby;}
 markConnected(clientId,connected){const lobby=this.forClient(clientId),p=lobby?.players.get(clientId);if(p){p.connected=!!connected;this.touch(lobby);}return lobby;}
 leave(clientId,save=true){const code=this.clientLobby.get(clientId);if(!code)return null;const lobby=this.lobbies.get(code);this.clientLobby.delete(clientId);if(!lobby)return null;lobby.players.delete(clientId);if(!lobby.players.size){this.lobbies.delete(code);if(save)this.scheduleSave();return null;}if(lobby.hostId===clientId)lobby.hostId=lobby.players.keys().next().value;this.touch(lobby,save);return lobby;}
 forClient(clientId){const code=this.clientLobby.get(clientId);return code?this.lobbies.get(code):null;}
 campaignSnapshot(c){if(!c)return null;ensureCampaignRuntime(c);const now=Date.now();return {id:c.id,phase:c.phase,day:c.day,createdAt:c.createdAt,startedAt:c.startedAt,dayDurationMs:c.dayDurationMs,preparationMs:c.preparationMs,prepRemainingMs:c.phase==='preparing'?Math.max(0,c.prepEndsAt-now):0,nextDayInMs:c.phase==='running'?Math.max(0,c.nextDayAt-now):null,serverNow:now,playerStates:c.playerStates||{},cityOwners:c.cityOwners||{},wars:c.wars||{},truces:c.truces||{},battles:c.battles||[],sieges:c.sieges||[],occupations:c.occupations||{},peaceOffers:c.peaceOffers||[],alliances:c.alliances||{},allianceOffers:c.allianceOffers||[],tradeOffers:c.tradeOffers||[],aiCountries:c.aiCountries||{}};}
 snapshot(lobby){return {code:lobby.code,hostId:lobby.hostId,status:lobby.status,gameId:lobby.gameId||null,players:[...lobby.players.values()].map(p=>({...p,host:p.id===lobby.hostId})),maxPlayers:MAX_PLAYERS,campaign:this.campaignSnapshot(lobby.campaign)};}
 touch(lobby,save=true){if(lobby)lobby.updatedAt=Date.now();if(save)this.scheduleSave();}
 campaignCommand(clientId,action,payload={}){
  const lobby=this.forClient(clientId);if(!lobby?.campaign||lobby.status!=='started')throw new Error('No active shared campaign.');const c=ensureCampaignRuntime(lobby.campaign),state=ensureCampaignPlayerRuntime(c,c.playerStates?.[clientId]);if(!state)throw new Error('Your multiplayer realm was not found.');const day=Math.max(0,Math.floor(Number(c.day)||0)),owned=new Set(state.ownedCities||[]);
  const economy=handleEconomyCommand1300(c,clientId,action,payload,day);if(economy){this.touch(lobby);return {lobby,message:economy.message};}
  const pvp=handlePvPCommand(c,clientId,action,payload,day);if(pvp){this.touch(lobby);return {lobby,message:pvp.message};}
  if(action==='recruit'){
   const cityId=String(payload.cityId||''),unitId=String(payload.unitId||''),unit=MILITARY_UNIT_1300[unitId],amount=Math.max(1,Math.min(5000,Math.floor(Number(payload.amount)||0)));if(!owned.has(cityId))throw new Error('You can only recruit in your own province.');if(!unit?.professional)throw new Error('Choose a professional unit.');if(unit.tech)throw new Error(unit.name+' still requires its technology system to be shared in multiplayer.');const cap=playerProfessionalCap(state),used=playerArmyTotal(state)+pendingTrainingTotal(state);if(used+amount>cap)throw new Error('Professional army cap is 5% of your population. You can queue at most '+Math.max(0,cap-used)+' more soldiers.');const order={id:'mp-training-'+state.nextTrainingId++,cityId,unitId,amount,startDay:day,finishDay:day+unit.trainingDays};state.trainingQueues.push(order);addPlayerEvent(state,amount+' '+unit.name+' entered training in '+CITY_1300[cityId].name+'.',day);this.touch(lobby);return {lobby,message:amount+' '+unit.name+' entered training. Ready in '+unit.trainingDays+' game-days.'};
  }
  if(action==='move_army'){const result=startPvPMovement(c,clientId,payload,day);this.touch(lobby);return {lobby,message:result.message};}
  if(action==='build'){
   const cityId=String(payload.cityId||''),buildingId=String(payload.buildingId||''),city=CITY_1300[cityId],building=BUILDING_1300[buildingId];if(!owned.has(cityId)||!city)throw new Error('You can only build in your own province.');if(!building)throw new Error('Unknown building.');if(building.requiresCoast&&!isCoastalCity1300(city))throw new Error(building.name+' requires real sea access.');if(state.construction.some(j=>j.cityId===cityId&&j.buildingId===buildingId))throw new Error(building.name+' is already under construction here.');const level=multiplayerBuildingLevel(state,cityId,buildingId),max=Math.max(1,Number(building.maxLevel)||3);if(level>=max)throw new Error(building.name+' is already at maximum level.');const cost=buildingCost1300(building,level);if(Number(state.florins)<cost)throw new Error('You need ƒ'+round2(cost-Number(state.florins))+' more Florins.');const days=multiplayerConstructionDays(building,level,cost),job={id:'mp-build-'+state.nextConstructionId++,cityId,buildingId,startDay:day,completeDay:day+days,days,cost,fromLevel:level,toLevel:level+1};state.florins=round2(Number(state.florins)-cost);state.construction.push(job);addPlayerEvent(state,building.name+' level '+(level+1)+' construction started in '+city.name+'.',day);this.touch(lobby);return {lobby,message:building.name+' construction started for ƒ'+cost+'. Ready in '+days+' game-days.'};
  }
  throw new Error('Unknown multiplayer campaign command.');
 }
 tick(now=Date.now()){const changed=new Map();for(const lobby of this.lobbies.values()){const c=lobby.campaign;if(!c)continue;let stateChanged=false,major=false;if(c.phase==='preparing'){const sec=Math.ceil(Math.max(0,c.prepEndsAt-now)/1000);if(now>=c.prepEndsAt){c.phase='running';c.startedAt=now;c.nextDayAt=now+c.dayDurationMs;c.lastBroadcastSecond=null;stateChanged=true;}else if(sec!==c.lastBroadcastSecond){c.lastBroadcastSecond=sec;changed.set(lobby,false);}}
   if(c.phase==='running'&&now>=c.nextDayAt){const steps=Math.floor((now-c.nextDayAt)/c.dayDurationMs)+1;for(let i=0;i<steps;i++){c.day+=1;if(processCampaignSystems(c))major=true;}c.nextDayAt+=steps*c.dayDurationMs;stateChanged=true;}
   if(stateChanged){this.scheduleSave();changed.set(lobby,major||changed.get(lobby)||false);}
  }return [...changed.entries()].map(([lobby,major])=>({lobby,major}));}
 serializeLobby(lobby){const c=lobby.campaign,now=Date.now();return {code:lobby.code,hostId:lobby.hostId,status:lobby.status,gameId:lobby.gameId||null,createdAt:lobby.createdAt,updatedAt:lobby.updatedAt,players:[...lobby.players.values()].map(p=>({...p,connected:false})),campaign:c?{id:c.id,phase:c.phase,day:c.day,createdAt:c.createdAt,startedAt:c.startedAt,dayDurationMs:c.dayDurationMs,preparationMs:c.preparationMs,prepRemainingMs:c.phase==='preparing'?Math.max(0,c.prepEndsAt-now):0,nextDayInMs:c.phase==='running'?Math.max(1,c.nextDayAt-now):null,playerStates:c.playerStates||{},cityOwners:c.cityOwners||{},wars:c.wars||{},truces:c.truces||{},battles:c.battles||[],sieges:c.sieges||[],occupations:c.occupations||{},peaceOffers:c.peaceOffers||[],alliances:c.alliances||{},allianceOffers:c.allianceOffers||[],tradeOffers:c.tradeOffers||[],aiCountries:c.aiCountries||{},nextBattleId:c.nextBattleId||1,nextSiegeId:c.nextSiegeId||1,nextPeaceOfferId:c.nextPeaceOfferId||1,nextAllianceOfferId:c.nextAllianceOfferId||1,nextTradeOfferId:c.nextTradeOfferId||1}:null};}
 scheduleSave(){if(this.saveTimer)return;this.saveTimer=setTimeout(()=>{this.saveTimer=null;this.save();},250);}
 save(){try{fs.mkdirSync(path.dirname(SAVE_FILE),{recursive:true});const payload={version:1,savedAt:Date.now(),lobbies:[...this.lobbies.values()].map(l=>this.serializeLobby(l))},tmp=SAVE_FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(payload,null,2));fs.renameSync(tmp,SAVE_FILE);}catch(e){console.error('Multiplayer save failed:',e.message);}}
 load(){try{if(!fs.existsSync(SAVE_FILE))return;const raw=JSON.parse(fs.readFileSync(SAVE_FILE,'utf8')),now=Date.now();for(const saved of raw.lobbies||[]){const maxAge=saved.status==='started'?CAMPAIGN_TTL_MS:WAITING_TTL_MS;if(now-(saved.updatedAt||saved.createdAt||now)>maxAge)continue;const players=new Map((saved.players||[]).map(p=>[p.id,{...p,connected:false}]));if(!players.size)continue;const c=saved.campaign?{...saved.campaign,prepEndsAt:null,nextDayAt:null,lastBroadcastSecond:null}:null;if(c){if(c.phase==='preparing')c.prepEndsAt=now+Math.max(0,Number(c.prepRemainingMs)||0);else if(c.phase==='running')c.nextDayAt=now+Math.max(1,Number(c.nextDayInMs)||c.dayDurationMs||DAY_MS);delete c.prepRemainingMs;delete c.nextDayInMs;}const lobby={...saved,players,campaign:c};this.lobbies.set(lobby.code,lobby);for(const id of players.keys())this.clientLobby.set(id,lobby.code);}}catch(e){console.error('Multiplayer save load failed:',e.message);}}
 cleanup(){const now=Date.now();for(const [code,lobby] of this.lobbies){const ttl=lobby.status==='started'?CAMPAIGN_TTL_MS:WAITING_TTL_MS;if(now-(lobby.updatedAt||lobby.createdAt)>ttl){for(const id of lobby.players.keys())this.clientLobby.delete(id);this.lobbies.delete(code);}}this.scheduleSave();}
}
const store=new LobbyStore(),connections=new Map();
const server=http.createServer((req,res)=>{if(req.url==='/health'){res.writeHead(200,{'content-type':'application/json','access-control-allow-origin':'*'});res.end(JSON.stringify({ok:true,lobbies:store.lobbies.size,campaigns:[...store.lobbies.values()].filter(x=>x.campaign).length,maxPlayers:MAX_PLAYERS}));return;}res.writeHead(200,{'content-type':'text/plain'});res.end('Cardwars multiplayer server\n');});
const wss=new WebSocketServer({server});
const broadcast=lobby=>{if(!lobby)return;const payload={type:'lobby_state',lobby:store.snapshot(lobby)};for(const p of lobby.players.values())send(connections.get(p.id),payload);};
const broadcastCampaign=lobby=>{if(!lobby?.campaign)return;const payload={type:'campaign_state',campaign:store.campaignSnapshot(lobby.campaign),lobby:store.snapshot(lobby)};for(const p of lobby.players.values())send(connections.get(p.id),payload);};
const broadcastCampaignUpdate=lobby=>{if(!lobby?.campaign)return;const payload={type:'campaign_update',campaign:store.campaignSnapshot(lobby.campaign),lobby:store.snapshot(lobby)};for(const p of lobby.players.values())send(connections.get(p.id),payload);};
const error=(ws,message)=>send(ws,{type:'error',message});

wss.on('connection',ws=>{let clientId=null;
 ws.on('message',raw=>{let msg;try{msg=JSON.parse(String(raw));}catch{return error(ws,'Invalid message.');}try{
  if(msg.type==='identify'){clientId=String(msg.clientId||'').slice(0,80);if(!clientId)throw new Error('Missing client ID.');const old=connections.get(clientId);if(old&&old!==ws){try{old.close();}catch{}}connections.set(clientId,ws);const lobby=store.markConnected(clientId,true);if(lobby){broadcast(lobby);if(lobby.campaign)broadcastCampaign(lobby);}return;}
  if(!clientId||String(msg.clientId||'')!==clientId)throw new Error('Identify before using multiplayer.');
  if(msg.type==='create_lobby'){broadcast(store.create(clientId,msg.player));return;}
  if(msg.type==='join_lobby'){broadcast(store.join(clientId,msg.code,msg.player));return;}
  if(msg.type==='resume_lobby'){const lobby=store.resume(clientId,msg.code,msg.player);broadcast(lobby);if(lobby.campaign)broadcastCampaign(lobby);return;}
  if(msg.type==='set_ready'){broadcast(store.setReady(clientId,msg.ready));return;}
  if(msg.type==='campaign_command'){try{const result=store.campaignCommand(clientId,String(msg.action||''),msg.payload||{});send(ws,{type:'command_result',ok:true,commandId:msg.commandId||null,message:result.message});broadcastCampaignUpdate(result.lobby);}catch(e){send(ws,{type:'command_result',ok:false,commandId:msg.commandId||null,message:e.message||'Campaign command failed.'});}return;}
  if(msg.type==='start_lobby'){const lobby=store.start(clientId);broadcast(lobby);const payload={type:'game_started',lobby:store.snapshot(lobby),campaign:store.campaignSnapshot(lobby.campaign)};for(const p of lobby.players.values())send(connections.get(p.id),payload);return;}
  if(msg.type==='leave_lobby'){const previous=store.forClient(clientId),remaining=store.leave(clientId);send(ws,{type:'left_lobby'});if(remaining)broadcast(remaining);else if(previous)store.scheduleSave();return;}
 }catch(e){error(ws,e.message||'Multiplayer action failed.');}});
 ws.on('close',()=>{if(!clientId)return;if(connections.get(clientId)===ws)connections.delete(clientId);const lobby=store.markConnected(clientId,false);broadcast(lobby);setTimeout(()=>{if(connections.has(clientId))return;const current=store.forClient(clientId);if(!current)return;if(current.status==='waiting'){const remaining=store.leave(clientId);if(remaining)broadcast(remaining);}else broadcast(current);},RECONNECT_GRACE_MS);});
});
setInterval(()=>{for(const row of store.tick())(row.major?broadcastCampaignUpdate:broadcastCampaign)(row.lobby);},250).unref();
setInterval(()=>store.cleanup(),10*60*1000).unref();
const shutdown=()=>{store.save();server.close(()=>process.exit(0));setTimeout(()=>process.exit(0),1000).unref();};process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown);
server.listen(PORT,'0.0.0.0',()=>console.log(`Cardwars multiplayer server listening on :${PORT}`));
