(()=>{"use strict";const data=window.CARDWARS_MAP_DATA;if(!data?.cities?.length)return;const NS="http://www.w3.org/2000/svg",svg=document.querySelector("#map"),land=document.querySelector("#land"),cityLayer=document.querySelector("#cities"),labelLayer=document.querySelector("#labels"),canvas=document.querySelector("#draw-layer"),ctx=canvas.getContext("2d"),initial={x:45,y:0,w:840,h:590},view={...initial};let active=null,drag=false,start=null,viewStart=null,labelMode="smart",mode="pan",drawing=null;const strokes=JSON.parse(localStorage.getItem("cardwars-map-drawings-v2")||"[]");land.setAttribute("d",data.landPath);document.querySelector("#city-count").textContent=data.cities.length;const prioritized=[...data.cities].sort((a,b)=>b.population-a.population),nodes=new Map;
for(const city of data.cities){const dot=document.createElementNS(NS,"circle");dot.classList.add("city-dot");dot.setAttribute("cx",city.x);dot.setAttribute("cy",city.y);dot.setAttribute("r","1.25");dot.setAttribute("tabindex","0");dot.setAttribute("aria-label",city.name+", "+city.country);dot.onclick=e=>{e.stopPropagation();select(city,dot)};dot.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();select(city,dot)}};cityLayer.append(dot);const label=document.createElementNS(NS,"text");label.classList.add("city-label");label.setAttribute("x",city.x+3);label.setAttribute("y",city.y-2.5);label.textContent=city.name;labelLayer.append(label);nodes.set(city.id,{label})}
function select(city,dot){active?.classList.remove("selected");active=dot;dot.classList.add("selected");document.querySelector("#city-name").textContent=city.name;document.querySelector("#city-country").textContent=city.country;document.querySelector("#city-card").hidden=false}
function apply(){svg.setAttribute("viewBox",view.x+" "+view.y+" "+view.w+" "+view.h);const scale=view.w/Math.max(svg.clientWidth,1),r=Math.min(2.15,Math.max(.95,scale*1.18));document.querySelectorAll(".city-dot").forEach(d=>d.setAttribute("r",r));labelLayer.style.fontSize=Math.min(10.5,Math.max(7,scale*8.3))+"px";updateLabels();renderStrokes()}
function updateLabels(){const labels=[...document.querySelectorAll(".city-label")];labels.forEach(l=>l.style.display="none");if(labelMode==="off")return;if(labelMode==="all"){labels.forEach(l=>l.style.display="");return}const boxes=[],max=Math.round(38+initial.w/view.w*28);let shown=0;for(const city of prioritized){if(shown>=max)break;const l=nodes.get(city.id).label;l.style.display="";const b=l.getBoundingClientRect(),p={l:b.left-3,r:b.right+3,t:b.top-2,b:b.bottom+2};if(boxes.some(q=>!(p.r<q.l||p.l>q.r||p.b<q.t||p.t>q.b)))l.style.display="none";else{boxes.push(p);shown++}}}
function zoom(f,sx=svg.clientWidth/2,sy=svg.clientHeight/2){const r=svg.getBoundingClientRect(),px=(sx-r.left)/r.width,py=(sy-r.top)/r.height,nw=Math.min(initial.w*1.15,Math.max(120,view.w*f)),nh=nw*view.h/view.w;view.x+=(view.w-nw)*px;view.y+=(view.h-nh)*py;view.w=nw;view.h=nh;apply()}
svg.onwheel=e=>{e.preventDefault();zoom(e.deltaY>0?1.13:.885,e.clientX,e.clientY)};svg.onpointerdown=e=>{if(mode!=="pan"||e.target.classList.contains("city-dot"))return;drag=true;start={x:e.clientX,y:e.clientY};viewStart={x:view.x,y:view.y};svg.setPointerCapture(e.pointerId);svg.classList.add("dragging")};svg.onpointermove=e=>{if(!drag)return;view.x=viewStart.x-(e.clientX-start.x)*view.w/svg.clientWidth;view.y=viewStart.y-(e.clientY-start.y)*view.h/svg.clientHeight;apply()};svg.onpointerup=svg.onpointercancel=()=>{drag=false;svg.classList.remove("dragging")};
function resize(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);ctx.setTransform(d,0,0,d,0,0);renderStrokes()}
function mapToCanvas(p){const m=svg.getScreenCTM(),r=canvas.getBoundingClientRect(),q=new DOMPoint(p[0],p[1]).matrixTransform(m);return[q.x-r.left,q.y-r.top]}
function eventToMap(e){const q=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse());return[q.x,q.y]}
function renderStrokes(){const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);ctx.lineCap=ctx.lineJoin="round";for(const s of strokes){if(s.points.length<2)continue;ctx.beginPath();s.points.forEach((p,i)=>{const q=mapToCanvas(p);i?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1])});ctx.strokeStyle=s.color;ctx.lineWidth=s.width;ctx.stroke()}}
function save(){localStorage.setItem("cardwars-map-drawings-v2",JSON.stringify(strokes))}
function eraseAt(e){const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;for(let k=strokes.length-1;k>=0;k--){const pts=strokes[k].points;for(let i=1;i<pts.length;i++){const a=mapToCanvas(pts[i-1]),b=mapToCanvas(pts[i]),dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((x-a[0])*dx+(y-a[1])*dy)/(dx*dx+dy*dy||1))),d=Math.hypot(x-(a[0]+t*dx),y-(a[1]+t*dy));if(d<12){strokes.splice(k,1);save();renderStrokes();return}}}}
canvas.onpointerdown=e=>{if(mode==="draw"){drawing={color:document.querySelector("#draw-color").value,width:3,points:[eventToMap(e)]};strokes.push(drawing)}else if(mode==="erase")eraseAt(e);canvas.setPointerCapture(e.pointerId)};
canvas.onpointermove=e=>{if(mode==="draw"&&drawing){const p=eventToMap(e),last=drawing.points.at(-1);if(Math.hypot(p[0]-last[0],p[1]-last[1])>.15)drawing.points.push(p);renderStrokes()}else if(mode==="erase"&&e.buttons)eraseAt(e)};
canvas.onpointerup=canvas.onpointercancel=()=>{if(drawing){save();drawing=null}};
document.querySelectorAll(".mode").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll(".mode").forEach(x=>x.classList.toggle("active",x===b));canvas.style.pointerEvents=mode==="pan"?"none":"auto"});document.querySelector("#clear-drawing").onclick=()=>{if(strokes.length&&confirm("Alle getekende lijnen wissen?")){strokes.length=0;save();renderStrokes()}};document.querySelector("#export-drawing").onclick=()=>{const payload={format:"cardwars-map-drawing",version:2,coordinateSystem:"svg-map",viewBox:initial,strokes};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="cardwars-nieuwe-kaart.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};document.querySelector("#zoom-in").onclick=()=>zoom(.82);document.querySelector("#zoom-out").onclick=()=>zoom(1.22);document.querySelector("#reset").onclick=()=>{Object.assign(view,initial);apply()};document.querySelector("#close-card").onclick=()=>document.querySelector("#city-card").hidden=true;document.querySelector("#label-mode").onclick=e=>{labelMode=labelMode==="smart"?"all":labelMode==="all"?"off":"smart";e.currentTarget.textContent="Namen: "+({smart:"slim",all:"allemaal",off:"uit"}[labelMode]);updateLabels()};addEventListener("resize",()=>{apply();resize()});apply();resize()})();