import {CITIES,CITY,RARITIES,RARITY_COLORS,DUPLICATE_COINS,PACK} from './data.js';
import {freshProfile,formatNumber,openPack,validateProfile} from './engine.js';
import {icon} from './icons.js';
import {WorldMap} from './map.js';
const $=s=>document.querySelector(s),app=$('#app'),modal=$('#modal'),KEY='cardwars.collection.v2';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let profile=freshProfile(),storageFailed=false;
try{const raw=localStorage.getItem(KEY);if(raw){const p=JSON.parse(raw);if(validateProfile(p))profile=p;else storageFailed=true;}}catch{storageFailed=true;}
let view='collection',filter='all',rarity='all',country='all',search='',world=null,selected='rome',atlasRegion=null,atlasSearch='',packResult=[],revealed=new Set(),toastTimer;
const mapState={selected,collection:profile.collection};
const REALMS=[...new Set(CITIES.map(c=>c.realm))].sort((a,b)=>a.localeCompare(b));
const count=()=>Object.keys(profile.collection).length;
function button(text,action,cls='secondary',extra=''){return `<button class="btn ${cls}" data-action="${action}" ${extra}>${text}</button>`;}
function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4200);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(profile));}catch{storageFailed=true;toast('Browser storage is unavailable. Export your collection from the guide.');}}
function flag(){return `<span class="realm-sigil" aria-hidden="true">${icon('crown')}</span>`;}
function header(){return `<header class="lobby-header"><button class="brand" data-action="collection" aria-label="Cardwars home"><span class="brand-mark">${icon('crown')}</span><span>CARDWARS<small>THE AGE OF REALMS</small></span></button><nav aria-label="Main navigation">${[['collection','cards','Collection'],['packs','pack','Packs'],['game','army','Game'],['atlas','globe','Map']].map(([id,i,label])=>`<button class="${view===id?'active':''}" data-action="${id}">${icon(i)}<span>${label}</span>${id==='packs'?'<b class="nav-badge free-badge">FREE</b>':''}</button>`).join('')}</nav><div class="header-tools"><span class="seal-count" title="Coins earned from duplicate city cards">${icon('coins')} <strong id="coin-total">${profile.coins.toLocaleString('en-GB')}</strong> <small>coins</small></span><button class="reset-button" data-action="reset" title="Reset collection and coins">Reset</button><button class="icon-btn" data-action="help" aria-label="Game guide and saves">${icon('help')}</button></div></header>`;}
function footer(){return `<footer class="lobby-footer"><span>CONTINENTAL EUROPE · c. 600 CE</span><span class="save-note">${icon('save')} ${storageFailed?'Export a save to keep your progress':'Saved on this device'}</span><button data-action="sources">Historical notes & image credits ${icon('arrow')}</button></footer>`;}
function stat(key,label,value){const icons={food:'wheat',army:'army',navy:'navy',people:'people',size:'size',technology:'tech',satisfaction:'happy'};return `<div class="stat"><span>${icon(icons[key])}${label}</span><strong>${value}</strong></div>`;}
function card(c,compact=false){const owned=!!profile.collection[c.id];return `<button class="city-card rarity-${c.rarity} ${owned?'':'locked'} ${compact?'compact':''}" style="--rarity:${RARITY_COLORS[c.rarity]}" data-action="card" data-id="${c.id}" aria-label="Inspect ${esc(c.name)}, ${c.country}, ${RARITIES[c.rarity]}, ${owned?'collected':'undiscovered'}"><div class="card-photo"><img src="${c.image}" alt="Present-day view of ${esc(c.modern)} or its historic site" loading="${compact?'eager':'lazy'}"><span class="rarity-chip">${icon(c.rarity>2?'star':'globe')}${RARITIES[c.rarity]}</span><span class="card-number">${String(c.index+1).padStart(3,'0')}</span><div class="card-city"><span class="card-country">${flag(c)} ${c.country}</span><h3 class="${c.name.length>16?'long-name':''}">${c.name}</h3><small>${c.name===c.modern?'Late-antique city':c.modern}</small></div></div><div class="card-stats">${stat('army','Army',formatNumber(c.army,'army'))}${stat('navy','Navy',formatNumber(c.navy,'navy'))}${stat('people','People',formatNumber(c.people))}${stat('size','Size',formatNumber(c.size,'size'))}<div class="card-scores">${[['Food',c.food],['Technology',c.technology],['Satisfaction',c.satisfaction]].map(([label,n])=>`<div><span>${label}</span><strong>${n}<small>/100</small></strong><i style="--value:${n}%"></i></div>`).join('')}</div></div><div class="card-foot"><span>${owned?(profile.collection[c.id]>1?`${profile.collection[c.id]} copies`:`${icon('check')} Collected`):`${icon('lock')} Undiscovered`}</span><span>${icon('coins')} ${DUPLICATE_COINS[c.rarity]} per duplicate</span></div></button>`;}
function render(){world?.destroy();world=null;app.className=view==='atlas'?'lobby atlas-view':'lobby';app.innerHTML=header()+(view==='collection'?collectionPage():view==='packs'?packsPage():view==='game'?gamePage():atlasPage())+(view==='atlas'?'':footer());if(view==='collection')renderGrid();if(view==='atlas'){renderAtlasPanel();mapState.selected=selected;mapState.collection=profile.collection;world=new WorldMap($('#map-host'),mapState,id=>{selected=id;mapState.selected=id;atlasRegion=null;renderAtlasPanel();world.refresh();app.classList.add('show-panel');},region=>{atlasRegion=region;atlasSearch='';renderAtlasPanel();app.classList.add('show-panel');});}}
function collectionPage(){return `<main class="collection-page"><div class="page-title"><div><span class="eyebrow">THE FIRST CHAPTER · EUROPE</span><h1>The collection<span class="title-dot">.</span></h1><p>${CITIES.length} cities. ${REALMS.length} historical realms. A world waiting to be discovered.</p></div><div class="collection-progress"><strong>${String(count()).padStart(2,'0')}<span> / ${CITIES.length}</span></strong><span>CITIES DISCOVERED</span><div><i style="width:${count()/CITIES.length*100}%"></i></div></div></div>${!count()?`<div class="collection-empty"><div>${icon('pack')}<div><strong>Your first discovery is waiting.</strong><p>Open a free pack to reveal five cities. Collected cards come to life in colour.</p></div></div>${button('Open a free pack '+icon('arrow'),'packs','primary')}</div>`:''}<div class="collection-toolbar"><div class="segmented"><button class="${filter==='all'?'active':''}" data-action="filter" data-id="all">All cities <small>${CITIES.length}</small></button><button class="${filter==='owned'?'active':''}" data-action="filter" data-id="owned">Collected <small>${count()}</small></button></div><div class="filters"><label class="search-input">${icon('search')}<input id="city-search" aria-label="Search cities" placeholder="Find a city…" value="${esc(search)}"></label><select id="country-filter" aria-label="Filter by historical realm"><option value="all">All realms</option>${REALMS.map(label=>`<option value="${esc(label)}" ${country===label?'selected':''}>${label}</option>`).join('')}</select><select id="rarity-filter" aria-label="Filter by rarity"><option value="all">All rarities</option>${RARITIES.map((r,i)=>`<option value="${i}" ${rarity===String(i)?'selected':''}>${r}</option>`).join('')}</select></div></div><div class="collection-meta"><span id="result-count"></span><span>Historical political realms · c. 600 CE</span></div><div id="card-grid" class="card-grid"></div></main>`;}
function renderGrid(){const list=CITIES.filter(c=>(filter==='all'||profile.collection[c.id])&&(rarity==='all'||c.rarity===+rarity)&&(country==='all'||c.realm===country)&&`${c.name} ${c.modern} ${c.modernCountry} ${c.realm}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.rarity-a.rarity||a.name.localeCompare(b.name));$('#result-count').textContent=`${list.length} ${list.length===1?'city':'cities'}`;$('#card-grid').innerHTML=list.length?list.map(c=>card(c)).join(''):`<div class="no-results">${icon('search')}<h3>${filter==='owned'&&!count()?'No discoveries yet':'No cities found'}</h3><p>${filter==='owned'&&!count()?'Your first five cards are one free pack away.':'Try another city, realm or rarity.'}</p>${button(filter==='owned'&&!count()?'Open a free pack':'Clear filters',filter==='owned'&&!count()?'packs':'clear-filters')}</div>`;}
function packsPage(){return `<main class="packs-page"><div class="page-title"><div><span class="eyebrow">DISCOVER THE OLD WORLD</span><h1>Five cards. A new beginning<span class="title-dot">.</span></h1><p>Every pack is free. Every city has a story.</p></div><span class="pack-free-pill">UNLIMITED FREE PACKS</span></div><div class="single-pack-layout"><section class="pack-stage"><div class="pack-orbit"></div><div class="pack-art pack-1" aria-hidden="true"><div class="pack-frame"><span class="pack-edition">THE AGE OF REALMS</span><div class="pack-crest">${icon('crown')}</div><strong>CARDWARS</strong><span class="pack-type">EUROPE</span><i></i><small>5 CITY CARDS · VOL. I</small></div></div><span class="pack-stage-label">THE CONTINENTAL COLLECTION</span></section><section class="pack-description"><span class="eyebrow">VOLUME I · c. 600 CE</span><h2>Europe pack</h2><p>Uncover five cities from the old continent, from small frontier settlements to the great imperial capitals.</p><div class="pack-highlights"><span>${icon('cards')} 5 cards per pack</span><span>${icon('coins')} No coins required</span><span>${icon('globe')} ${CITIES.length} cities to discover</span></div>${button('Open free pack '+icon('arrow'),'open-pack','primary large-button')}<p class="pack-guarantee">No purchases. No waiting. Open as many as you like.</p><div class="pack-counters"><div><strong>${profile.packsOpened}</strong><span>PACKS OPENED</span></div><div><strong>${count()}</strong><span>UNIQUE CITIES</span></div><div><strong>${profile.drawn}</strong><span>CARDS DRAWN</span></div></div>${profile.lastPack.length?'<button class="text-btn" data-action="last-pack">View your last pack</button>':''}</section><aside class="drop-rates"><span class="eyebrow">KNOW YOUR ODDS</span><h3>A chance at greatness.</h3><p>Each of the five cards is drawn independently.</p>${RARITIES.map((r,i)=>`<div class="drop-rate"><span style="color:${RARITY_COLORS[i]}"><i></i>${r}</span><strong>${PACK.odds[i]}%</strong><small>+${DUPLICATE_COINS[i]} coins for a duplicate</small></div>`).join('')}<p class="duplicate-note">Already own a city? Keep the extra copy and receive coins based on its rarity.</p></aside></div></main>`;}
function gamePage(){return `<main class="game-empty"><span class="eyebrow">THE NEXT CHAPTER</span><h1>Game</h1><div class="empty-seal">${icon('army')}</div><p>The campaign is not available yet.</p></main>`;}
function atlasPage(){return `<div class="atlas-layout"><aside class="realm-panel" id="atlas-panel"></aside><main class="map-surface" id="map-host"></main><button class="atlas-panel-toggle" data-action="toggle-panel" aria-label="Show or hide city information">${icon('list')}</button></div>`;}
function polityType(name){for(const [needle,type] of [['Free Imperial City','Free Imperial City'],['Prince-Bishopric','Prince-Bishopric'],['Archbishopric','Archbishopric'],['Grand Duchy','Grand Duchy'],['Margraviate','Margraviate'],['Marquisate','Marquisate'],['Principality','Principality'],['Patriarchate','Patriarchate'],['Lordship','Lordship'],['Commune','Commune'],['Judicate','Judicate'],['Duchy','Duchy'],['County','County'],['Kingdom','Kingdom'],['Empire','Empire'],['Republic','Republic'],['Beylik','Beylik'],['Khanate','Khanate'],['Ilkhanate','Ilkhanate'],['Sultanate','Sultanate'],['Emirate','Emirate'],['Crown of','Composite monarchy'],['Order','Military Order'],['Papal States','Papal State'],['Waldstatte','Confederated communities']])if(name.includes(needle))return type;return 'Political entity';}
function polityDescription(name,detail){const type=polityType(name);if(type==='Free Imperial City')return 'A self-governing imperial city within the Holy Roman Empire, shown separately because it had substantial local autonomy.';if(type==='Prince-Bishopric'||type==='Archbishopric')return 'An ecclesiastical territory where the ruling bishop or archbishop also exercised temporal political power.';if(type==='Beylik')return 'A Turkish principality in the fragmented political landscape of Anatolia around 1300.';if(type==='Republic')return 'A republican polity represented as a separate power on the c. 1300 political map.';if(type==='Papal State')return 'Territory under the temporal rule of the papacy, represented separately from neighbouring Italian states.';return detail?'A distinct medieval polity in the detailed c. 1300 gameplay layer. Its fine borders are schematic approximations for map readability.':'A political entity shown on the approximate c. 1300 historical map.';}
function inAtlasRegion(){return true;}
function renderAtlasPanel(){const c=CITY[selected];if(atlasRegion){const type=polityType(atlasRegion.name);$('#atlas-panel').innerHTML=`<div class="atlas-panel-head polity-panel-head"><span class="eyebrow">POLITICAL MAP · c. 1300 CE</span><h2>${esc(atlasRegion.name)}</h2><p>${esc(type)}</p><div class="atlas-panel-switch"><button data-action="all-map-cities">Back to city atlas</button><button data-action="inspect-selected">Selected city ${icon('arrow')}</button></div></div><div class="polity-panel-body"><div class="polity-map-seal">${icon('crown')}<span><strong>${esc(type)}</strong><small>Approximate political entity · 1300</small></span></div><p>${esc(polityDescription(atlasRegion.name,atlasRegion.detail))}</p><div class="polity-facts"><span>Map period<strong>c. 1300 CE</strong></span><span>Boundary detail<strong>${atlasRegion.detail?'Detailed gameplay subdivision':'Historical basemap region'}</strong></span></div><p class="atlas-footnote">Click another country or territory on the map to inspect it. The city cards still use the older 600 CE data and will be converted separately.</p></div>`;return;}const list=CITIES.filter(c=>`${c.name} ${c.modern} ${c.modernCountry} ${c.realm}`.toLowerCase().includes(atlasSearch.toLowerCase()));$('#atlas-panel').innerHTML=`<div class="atlas-panel-head"><span class="eyebrow">CITY ATLAS</span><h2>The old continent</h2><p>${CITIES.length} city cards · map year 1300</p><div class="atlas-panel-switch"><button class="active" data-action="all-map-cities">All cities</button><button data-action="inspect-selected">Selected city ${icon('arrow')}</button></div></div><div class="atlas-feature"><img class="atlas-feature-photo" src="${c.image}" alt="Historic site of ${esc(c.modern)}"><div><span class="card-country">${flag(c)}${c.country}</span><h3>${c.name}</h3><p>${c.modern} · ${profile.collection[c.id]?'Collected':'Undiscovered'}</p>${button('Inspect card '+icon('arrow'),'card','small-btn',`data-id="${c.id}"`)}</div></div><div class="atlas-search-wrap"><label class="search-input">${icon('search')}<input id="atlas-search" aria-label="Find a city on the map" placeholder="Find a city…" value="${esc(atlasSearch)}"></label></div><div class="atlas-city-list" id="atlas-city-list">${mapList(list)}</div><p class="atlas-footnote">The map shows approximate political boundaries around 1300 CE. The city cards are still the 600 CE edition for now.</p>`;}
function mapList(list){return list.length?list.map(c=>`<button class="${selected===c.id?'selected':''}" data-action="map-city" data-id="${c.id}">${flag(c)}<span><strong>${c.name}</strong><small>${c.modern}</small></span>${profile.collection[c.id]?icon('check'):icon('arrow')}</button>`).join(''):'<p class="empty-map-list">No city cards in this region or search.</p>';}
function showDialog(html,cls=''){modal.className=cls;modal.innerHTML=`<button class="modal-close icon-btn" data-action="close" aria-label="Close dialog">${icon('close')}</button>${html}`;if(!modal.open)modal.showModal();modal.setAttribute('aria-label',modal.querySelector('h2')?.textContent||'Cardwars dialog');}
function inspectCard(id){const c=CITY[id];if(!c)return;showDialog(`<div class="detail-card">${card(c,true)}</div><div class="detail-copy"><span class="eyebrow">CITY CHARTER · c. 600 CE</span><h2>${c.name}</h2><div class="detail-country">${flag(c)}<span>${c.country}<small>Historical polity / political sphere · c. 600 CE</small></span></div><p class="lead">${c.description}</p><div class="detail-facts"><span>Present-day site<strong>${c.modern}, ${c.modernCountry}</strong></span><span>Your collection<strong>${profile.collection[id]?`${profile.collection[id]} ${profile.collection[id]===1?'copy':'copies'}`:'Not yet discovered'}</strong></span></div><p class="small muted">Game stats describe a city and its hinterland. The photograph shows its present-day site; the political label reflects the approximate c. 600 CE setting.</p>${button('Locate on the map '+icon('globe'),'locate','primary',`data-id="${id}"`)}<button class="text-btn" data-action="sources">Photo credits & historical notes</button></div>`,'card-dialog');}
function revealDialog(){const all=revealed.size===5,total=packResult.reduce((s,c)=>s+c.coins,0);showDialog(`<div class="reveal-heading"><span class="eyebrow">THE EUROPE PACK</span><h2>${all?'Five new chapters.':'Uncover your cities.'}</h2><p>${all?`${packResult.filter(r=>!r.duplicate).length} new discoveries · ${total} coins from duplicates`:'Select each card, or reveal them all.'}</p></div><div class="reveal-grid">${packResult.map((r,i)=>revealed.has(i)?`<div class="revealed-card">${card(CITY[r.id],true)}<span class="reveal-label">${r.duplicate?`DUPLICATE · +${r.coins} COINS`:'NEW CITY DISCOVERED'}</span></div>`:`<button class="card-back" data-action="reveal" data-id="${i}" aria-label="Reveal card ${i+1}"><span class="eyebrow">CARDWARS</span>${icon('crown')}<span>THE OLD WORLD</span><small>Tap to reveal</small></button>`).join('')}</div><div class="reveal-actions">${all?button('Open another pack','open-pack','secondary')+button('View collection '+icon('arrow'),'collection','primary'):button('Reveal all '+icon('star'),'reveal-all','primary')}</div>`,'reveal-dialog');}
function doOpenPack(){packResult=openPack(profile);revealed=new Set();save();render();revealDialog();}
function showReset(){showDialog(`<div class="simple-dialog"><span class="eyebrow">START AGAIN</span><h2>Reset everything?</h2><p>This removes every collected card, duplicate, coin and pack-opening record from this browser. All ${CITIES.length} city cards will become undiscovered again.</p><p>You can export a backup from the guide before resetting.</p><div class="dialog-actions">${button('Cancel','close')}${button('Reset collection & coins','confirm-reset','danger')}</div></div>`);}
function showHelp(){showDialog(`<div class="simple-dialog"><span class="eyebrow">A COLLECTOR’S COMPANION</span><h2>Discover the old world.</h2><div class="help-list"><div><b>01</b><span><strong>Open a free pack</strong>Every pack gives five city cards. There is no limit and no cost.</span></div><div><b>02</b><span><strong>Complete your collection</strong>All ${CITIES.length} cards are visible. Unknown cards are grey; collected cards are in colour. Search historical or modern city names.</span></div><div><b>03</b><span><strong>Earn coins from duplicates</strong>Common: 10 · Uncommon: 25 · Rare: 60 · Epic: 150 · Legendary: 400. Extra copies are kept. Coins are virtual and have no monetary value.</span></div><div><b>04</b><span><strong>Explore the map</strong>Drag to pan, scroll or pinch to zoom. Click, right-click or tap a city. The atlas currently uses approximate political boundaries around 1300 CE. Card realm data is still the 600 CE edition until it is updated separately.</span></div></div><div class="save-help"><h3>Your progress</h3><p>Saved in this browser on this device. Export a backup to keep or transfer it. There is no cloud sync.</p><div class="dialog-actions">${button(icon('download')+' Export collection','export')}${button('Import collection','import')}</div></div><button class="text-btn" data-action="sources">Historical notes & image credits</button></div>`);}
async function showSources(){showDialog(`<div class="simple-dialog"><span class="eyebrow">HISTORY & GEOGRAPHY</span><h2>Behind the cards.</h2><p>The collection draws on late-antique settlements around <strong>600 CE</strong>, after the fall of the Western Roman Empire. The Eastern Roman Empire still existed. Settlement size, continuity, names and local control sometimes changed rapidly in this period.</p><p><strong>Cards use historical political identities for c. 600 CE.</strong> Present-day city and country names are kept only as geographical references for locating the sites.</p><p>All numerical stats and rarities are authored game values, not historical census or military records. Size and people describe an abstract city with its hinterland. Food, technology and satisfaction use 0–100 scores. Navy is shown but has no gameplay yet.</p><p>Photographs show present-day cities or surviving sites. They may include later buildings. They have been resized, cropped and colour-treated for the cards.</p><h3>Historical map</h3><p>The atlas uses the c. 1300 layer from <a href="https://github.com/aourednik/historical-basemaps" target="_blank" rel="noopener">Historical Basemaps, André Ourednik and contributors</a>, under <a href="assets/historical-basemaps-LICENSE.txt" target="_blank" rel="noopener">GPL-3.0</a>. Boundaries and political control are approximate, especially in frontier regions. Card political labels are still the earlier 600 CE edition for now.</p><h3>Photograph credits</h3><div id="photo-credits">Loading credits…</div></div>`,'credits-dialog');try{const r=await fetch('assets/photo-credits.json');const photos=await r.json();if(!$('#photo-credits'))return;$('#photo-credits').innerHTML=photos.filter(p=>CITY[p.city]).sort((a,b)=>CITY[a.city].name.localeCompare(CITY[b.city].name)).map(p=>`<div class="credit-row"><strong>${CITY[p.city].name}</strong><span>${esc(p.author)} · ${esc(p.license)}</span><a href="${esc(p.source)}" target="_blank" rel="noopener">Original photograph</a> · <a href="${CITY[p.city].source}" target="_blank" rel="noopener">City / site article</a>${p.licenseUrl?` · <a href="${esc(p.licenseUrl)}" target="_blank" rel="noopener">Licence</a>`:''}</div>`).join('');}catch{if($('#photo-credits'))$('#photo-credits').innerHTML='<a href="assets/photo-credits.json">Open the credit file</a>';}}
function exportSave(){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(profile,null,2)],{type:'application/json'}));a.href=url;a.download='cardwars-collection.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Collection exported.');}
function navigate(next){modal.close();view=next;render();window.scrollTo(0,0);}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id;
 if(['collection','packs','game','atlas'].includes(a)){navigate(a);return;}
 if(a==='close')modal.close();if(a==='filter'){filter=id;render();}if(a==='clear-filters'){search='';country='all';rarity='all';filter='all';render();}
 if(a==='card'&&!(modal.open&&modal.classList.contains('card-dialog')))inspectCard(id);
 if(a==='open-pack')doOpenPack();if(a==='reveal'){revealed.add(+id);revealDialog();}if(a==='reveal-all'){packResult.forEach((_,i)=>revealed.add(i));revealDialog();}
 if(a==='last-pack'){packResult=profile.lastPack;revealed=new Set([0,1,2,3,4]);revealDialog();}
 if(a==='reset')showReset();if(a==='confirm-reset'){profile=freshProfile();mapState.collection=profile.collection;search='';country='all';rarity='all';filter='all';atlasSearch='';atlasRegion=null;selected='rome';packResult=[];revealed=new Set();try{localStorage.removeItem('cardwars.v1');}catch{}save();navigate('collection');toast('Collection reset. Every city is waiting to be discovered again.');}
 if(a==='locate'){selected=id;atlasRegion=null;atlasSearch='';navigate('atlas');world.focus(id);app.classList.add('show-panel');}
 if(a==='map-city'){selected=id;mapState.selected=id;atlasRegion=null;renderAtlasPanel();world.focus(id);app.classList.add('show-panel');}
 if(a==='inspect-selected')inspectCard(selected);if(a==='all-map-cities'){atlasRegion=null;atlasSearch='';renderAtlasPanel();}
 if(a==='toggle-panel')app.classList.toggle('show-panel');if(a==='help')showHelp();if(a==='sources')showSources();if(a==='export')exportSave();if(a==='import')$('#import-file').click();
});
document.addEventListener('input',e=>{if(e.target.id==='city-search'){search=e.target.value;renderGrid();}if(e.target.id==='atlas-search'){atlasSearch=e.target.value;const list=CITIES.filter(c=>inAtlasRegion(c)&&`${c.name} ${c.modern} ${c.modernCountry} ${c.realm}`.toLowerCase().includes(atlasSearch.toLowerCase()));$('#atlas-city-list').innerHTML=mapList(list);}});
document.addEventListener('change',e=>{if(e.target.id==='country-filter'){country=e.target.value;renderGrid();}if(e.target.id==='rarity-filter'){rarity=e.target.value;renderGrid();}});
$('#import-file').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>1000000)throw new Error();const p=JSON.parse(await file.text());if(!validateProfile(p))throw new Error();showDialog(`<div class="simple-dialog"><span class="eyebrow">RESTORE YOUR DISCOVERIES</span><h2>Import this collection?</h2><p>This replaces the current progress with ${Object.keys(p.collection).length} unique cities and ${p.coins.toLocaleString('en-GB')} coins.</p><div class="dialog-actions">${button('Cancel','close')}${button('Import and replace','confirm-import','primary')}</div></div>`);modal.querySelector('[data-action="confirm-import"]').addEventListener('click',()=>{profile=p;save();navigate('collection');toast('Collection imported.');},{once:true});}catch{toast('Invalid collection file. Your existing progress was kept.');}});
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
render();if(storageFailed)toast('A saved collection could not be loaded. You can import a backup from the guide.');
