import {BUILDING_1300, ECONOMY_1300, buildingAvailability1300} from './buildings1300.js?v=20260922-economy-v1';
import {GOODS_1300,GOOD_1300,RECIPES_1300,METHODS_1300,TRADE_LAWS_1300,provinceBuildings1300,sectorSettings1300,constructionQuote1300,creditLimit1300} from './economy1300.js?v=20260922-economy-v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(x,d=1)=>Number(x||0).toLocaleString('en-GB',{maximumFractionDigits:d});
const money=x=>'ƒ'+n(x,2);
const pct=x=>n(x*100,0)+'%';
const basket=x=>Object.entries(x||{}).map(([id,q])=>`${n(q)} ${GOOD_1300[id]?.name||id}`).join(' + ')||'Local land & labour';
const metric=(name,value,detail='')=>`<div><span>${name}</span><strong>${value}</strong>${detail?`<small>${detail}</small>`:''}</div>`;
const delta=x=>`${x<0?'−':'+'}${money(Math.abs(x))}`;
function methodSelect(game,c,b){const s=sectorSettings1300(game,c.id,b.id);return `<label>Production method<select data-economy="method" data-city="${c.id}" data-building="${b.id}" aria-label="${esc(b.name)} production method">${Object.entries(METHODS_1300).map(([id,m])=>`<option value="${id}" ${s.method===id?'selected':''} ${Number(c.technology)<m.technology?'disabled':''}>${m.name}${m.technology?' · tech '+m.technology:''}</option>`).join('')}</select></label>`;}
export function provinceIndustryHTML1300(game,c,b){
 const q=constructionQuote1300(game,c,b.id),r=RECIPES_1300[b.id];
 if(!r)return '';
 const m=game.economy.lastEconomy?.[c.id]?.[b.id],s=b.level?sectorSettings1300(game,c.id,b.id):null;
 return `<div class="industry-detail"><p class="chain-recipe"><b>Inputs</b> ${esc(basket(r.input))}<br><b>Outputs</b> ${esc(basket(r.output))}<small>Monthly base quantities per fully staffed level; actual output depends on workers, inputs and market access.</small></p>${q.pending?`<p class="econ-tag">${q.pending} upgrade${q.pending>1?'s':''} queued</p>`:''}${b.level?`<div class="industry-health"><span>Input supply <b>${pct(m?.fulfilment??1)}</b></span><span>Input costs <b>${money(m?.inputCost)}</b></span></div>${methodSelect(game,c,b)}<div class="industry-controls"><button data-action="economy-sector-toggle" data-city="${c.id}" data-id="${b.id}" data-key="subsidies" aria-pressed="${s.subsidy}">${s.subsidy?'Subsidised':'Subsidise losses'}</button><button data-action="economy-sector-toggle" data-city="${c.id}" data-id="${b.id}" data-key="paused" aria-pressed="${s.paused}">${s.paused?'Resume sector':'Pause sector'}</button></div>`:`<small>Construction needs ${esc(basket(q.materials))}. ${q.required} workdays at normal speed.</small>`}</div>`;
}
function overview(game,cities,policies,expenses){
 const e=game.economy,m=e.market,b=m.budget||{},balance=e.monthRevenue-e.monthExpenses;
 return `<section class="econ-intro"><span class="eyebrow">THE REALM'S LEDGER</span><h2>Prosperity is built.</h2><p>Supply your people, connect your workshops and keep the treasury solvent. Private businesses earn profits; the crown collects taxes and trade tolls.</p></section>
 <div class="econ-kpis">${metric('Treasury',money(game.florins),'Available for construction')}${metric('Forecast / month',delta(balance),'Settled from daily accruals')}${metric('Monthly production',money(m.gdp),'Gross output value, not treasury income')}${metric('Living standard',n(m.sol||50)+'/100','Prices, wages & essential needs')}</div>
 ${m.alerts.length?`<section class="econ-alerts" aria-label="Economic advice">${m.alerts.map(a=>`<p>${esc(a)}</p>`).join('')}</section>`:''}
 <section class="country-budget-table"><div class="country-budget-title"><span>MONTHLY FORECAST</span><small>Actual bills accrue each day</small></div>
 ${[['Company profit tax',b.sectorTax],['Household income levy',b.payrollTax],['Land & subsistence dues',b.landTax],['Trade tolls',b.tariffs]].map(([name,value])=>`<div><span>${name}</span><strong>+${money(value)}</strong></div>`).join('')}
 ${[['Army · ƒ0.005 per soldier',expenses.army],['Navy · ƒ0.02 per ship',expenses.navy],['Administration',expenses.stability],['Industry subsidies',b.subsidies],['Debt interest · 1.2% / month',expenses.interest]].map(([name,value])=>`<div><span>${name}</span><strong>−${money(value)}</strong></div>`).join('')}
 <div class="balance"><span>Forecast balance</span><strong class="${balance<0?'negative':''}">${delta(balance)}</strong></div>
 <div class="last-month"><span>${esc(e.lastMonthLabel||'No completed month')}</span><strong>${delta(e.lastMonthBalance||0)}</strong></div></section>
 <section class="econ-debt"><div><strong>Credit & obligations</strong><p>Debt ${money(m.debt)} / ${money(creditLimit1300(cities))} · Unpaid bills ${money(m.arrears)}</p><small>Deficits borrow automatically up to your credit limit. Unpaid bills increase unrest. Repayments clear unpaid bills first.</small></div><button data-action="economy-repay" ${m.debt+m.arrears<=0||game.florins<=0?'disabled':''}>Repay up to ƒ50</button></section>
 ${policies}
 <details class="econ-help"><summary>How this economy works</summary><p>One tick is one game day. Quantities shown are monthly rates in scaled gameplay units. Prices react to orders and reserves. Workshops require workers and physical inputs; unsold production goes into stock and earns no current sales income.</p><p>Every province has a rural subsistence hinterland. Private merchants import shortages and export surplus using limited caravan/port capacity. Import/export controls set priorities, not unlimited guaranteed deliveries. Foreign supply is an abstract market, not simulated foreign countries.</p><p>Construction takes timber, stone and tools over time. The first two queued projects build simultaneously. Masons and construction focus speed them up. Cancelled projects refund 75% of their uncompleted treasury cost; consumed materials stay consumed.</p><p>Companies contribute 8% of positive after-tax profits to the investment pool, which reimburses up to 25% of new construction. Wages are policy guidelines with local overrides, not a legal wage floor. The financial and population models are gameplay abstractions inspired by grand strategy games.</p></details>
 ${m.history.length?`<div class="econ-section-title">Last completed months</div><div class="econ-table-wrap"><table class="econ-table"><thead><tr><th>Month</th><th>Production</th><th>Living standard</th><th>Balance</th></tr></thead><tbody>${m.history.slice(-6).reverse().map(h=>`<tr><th>${esc(h.label)}</th><td>${money(h.gdp)}</td><td>${n(h.sol)}</td><td>${delta(h.balance)}</td></tr>`).join('')}</tbody></table></div>`:''}`;
}
function market(game){const m=game.economy.market;return `<div class="econ-section-title">The common market <small>${GOODS_1300.length} goods</small></div><p class="econ-copy">Prices in florins per unit; supply, orders and trade are monthly rates. Reserves are goods already available. Red shortages include unmet industry and household orders.</p>
 <div class="econ-policy-grid"><label>Trade law<select data-economy="trade-law">${Object.entries(TRADE_LAWS_1300).map(([id,l])=>`<option value="${id}" ${id===m.tradeLaw?'selected':''}>${l.name}</option>`).join('')}</select><small>${TRADE_LAWS_1300[m.tradeLaw].description}</small></label><div><span>Caravan & port capacity</span><strong>${n(m.tradeUsed)} / ${n(m.tradeCapacity)} units/month</strong><small>Warehouses, merchants, roads and dockyards expand capacity.</small></div></div>
 <section class="goods-market">${GOODS_1300.map(g=>{const r=m.goods[g.id],change=(r.price/g.basePrice-1)*100;return `<article class="good-card ${r.shortage>1?'scarce':''}"><header><div><small>${g.category}</small><strong>${g.name}</strong></div><div><b>${money(r.price)}</b><small class="${change>30?'negative':''}">${change>=0?'+':''}${n(change,0)}% vs base</small></div></header><div class="good-numbers">${metric('Production',n(r.supply))}${metric('Orders',n(r.demand))}${metric('Reserves',n(r.stock))}${metric('Unfilled',n(r.shortage))}</div><footer><span>In ${n(r.imports)} · Out ${n(r.exports)}</span>${g.tradable?`<label class="route-control"><span class="sr-only">${g.name} trade policy</span><select data-economy="route" data-good="${g.id}" aria-label="${g.name} trade policy">${[['auto','Auto trade'],['import','Import priority'],['export','Export surplus'],['off','No trade']].map(([id,label])=>`<option value="${id}" ${m.routes[g.id]===id?'selected':''}>${label}</option>`).join('')}</select></label>`:'<span>Local only</span>'}</footer></article>`;}).join('')}</section>`;}
function construction(game,cities){const m=game.economy.market;return `<div class="econ-kpis">${metric('Projects',m.queue.length,'Two active construction slots')}${metric('Private investment',money(m.investmentPool),'Up to 25% back on new projects')}</div>
 <div class="econ-policy-grid"><label>Construction pace<select data-economy="focus"><option value="balanced" ${m.constructionFocus==='balanced'?'selected':''}>Balanced</option><option value="building" ${m.constructionFocus==='building'?'selected':''}>Construction focus · ×1.5</option></select><small>Faster construction consumes materials faster, competing with workshops.</small></label><p>Building costs cover the full project. Timber, stone and tools must also be available in the market. Missing materials slow progress.</p></div>
 <section class="construction-queue">${m.queue.length?m.queue.map((q,i)=>`<article><div class="queue-number">${i+1}</div><div><strong>${esc(BUILDING_1300[q.buildingId].name)}</strong><small>${esc(cities.find(c=>c.id===q.cityId)?.name)} · ${i<2?esc(q.status||'Ready to build'):'Waiting for a slot'}</small><progress max="${q.required}" value="${q.work}" aria-label="Construction progress"></progress><small>${n(q.work)} / ${q.required} workdays · ${pct(q.work/q.required)}</small></div><button data-action="economy-cancel" data-index="${i}" aria-label="Cancel ${esc(BUILDING_1300[q.buildingId].name)}">Cancel</button></article>`).join(''):'<div class="econ-empty"><strong>Your builders are ready.</strong><p>Choose a province below and queue your next investment.</p></div>'}</section>
 <div class="econ-section-title">Invest by province <small>${Object.keys(BUILDING_1300).length} building types · ${ECONOMY_1300.maxBuildingLevel} levels</small></div>
 <section class="economy-provinces">${cities.map(c=>{const buildings=provinceBuildings1300(game,c),available=buildings.filter(b=>buildingAvailability1300(c,b).ok&&b.level<ECONOMY_1300.maxBuildingLevel);return `<article><div><strong>${esc(c.name)}</strong><small>${buildings.reduce((n,b)=>n+b.level,0)} built levels · ${available.length} sectors available to expand</small></div><button data-action="economy-province" data-id="${c.id}">Develop province →</button></article>`;}).join('')}</section>`;}
function production(game,cities){const e=game.economy;return `<div class="econ-section-title">Production & employment</div><p class="econ-copy">Upgrade methods to produce more with fewer workers, but supply extra tools. Priority determines who hires first. Subsidies charge the crown for losses; pausing a sector releases its workers.</p>
 ${cities.map(c=>`<details class="production-province" ${cities.length===1?'open':''}><summary><strong>${esc(c.name)}</strong><span>Market access ${pct(e.market.population[c.id].access)}</span></summary>${provinceBuildings1300(game,c).filter(b=>b.level>0).map(b=>{const v=e.lastEconomy?.[c.id]?.[b.id]||{},settings=sectorSettings1300(game,c.id,b.id);return `<article class="production-row"><div class="production-title"><strong>${esc(b.name)}</strong><span>Level ${b.level} · ${n(v.workers,0)} / ${n(v.capacity||b.maxWorkers*b.level,0)} workers</span><b class="${v.profit<0?'negative':''}">${money(v.profit)} / month</b></div><p>${esc(basket(RECIPES_1300[b.id].input))} → ${esc(basket(RECIPES_1300[b.id].output))}</p><small>Inputs supplied ${pct(v.fulfilment??1)} · Wages ${money(v.wageBill)} · Materials ${money(v.inputCost)} · Sales ${money(v.gross)}</small><div class="production-settings">${methodSelect(game,c,b)}<label>Hiring priority<select data-economy="priority" data-city="${c.id}" data-building="${b.id}">${[[1,'Normal'],[2,'High'],[3,'Essential']].map(([id,name])=>`<option value="${id}" ${settings.priority===id?'selected':''}>${name}</option>`).join('')}</select></label></div><div class="industry-controls"><button data-action="economy-sector-toggle" data-city="${c.id}" data-id="${b.id}" data-key="subsidies" aria-pressed="${settings.subsidy}">${settings.subsidy?'Subsidy on · '+money(v.subsidy):'Subsidise losses'}</button><button data-action="economy-sector-toggle" data-city="${c.id}" data-id="${b.id}" data-key="paused" aria-pressed="${settings.paused}">${settings.paused?'Resume production':'Pause production'}</button></div></article>`;}).join('')}</details>`).join('')}`;}
function society(game,cities){const m=game.economy.market;return `<div class="econ-kpis">${metric('Living standard',n(m.sol||50)+'/100')}${metric('Needs supplied',pct(m.fulfilment??1))}${metric('Urban employment',n(m.workers,0),'of '+n(m.workforce,0)+' available workers')}${metric('Harvest factor','×'+n(m.season||1,2),'Grain output follows the seasons')}</div><p class="econ-copy">People need grain, food, fuel, salt, clothing and services. Prosperous households demand more ale, wine and glass. Workers outside organised sectors live from the rural subsistence economy. This model tracks province households rather than individual people.</p>
 <section class="society-provinces">${cities.map(c=>{const p=m.population[c.id];return `<article><header><strong>${esc(c.name)}</strong><span>${n(c.people,0)} people</span></header><div class="good-numbers">${metric('Living standard',n(p.sol)+'/100')}${metric('Needs supplied',pct(p.fulfilment))}${metric('Urban employment',pct(p.employment))}${metric('Unrest',n(p.unrest)+'/100')}</div><p>${p.sol>=65?'Prosperous households':p.sol>=45?'Modest living conditions':'Households under pressure'} · ${p.fulfilment<.8?'Essential shortages need attention':'Basic supply is holding up'}</p></article>`;}).join('')}</section><div class="econ-section-title">What improves prosperity?</div><ul class="econ-advice"><li>Keep food and grain affordable through farms, fisheries, mills, bakers and imports.</li><li>Connect industries with roads and warehouses to protect market access.</li><li>Raise wages carefully: workers benefit, but expensive payroll can make companies unprofitable.</li><li>Match new factories to available workers and input resources.</li><li>Keep taxes and debt service low enough to support household purchasing power.</li></ul>`;}
export function economyDashboard1300(game,cities,{tab='overview',policies='',expenses={}}={}){
 return `<div class="economy-dashboard"><nav class="economy-tabs" aria-label="Economic departments">${[['overview','Overview'],['market','Market'],['construction','Construction'],['production','Production'],['society','Society']].map(([id,name])=>`<button data-action="economy-tab" data-id="${id}" class="${tab===id?'active':''}" aria-current="${tab===id?'page':'false'}">${name}</button>`).join('')}</nav>${tab==='market'?market(game):tab==='construction'?construction(game,cities):tab==='production'?production(game,cities):tab==='society'?society(game,cities):overview(game,cities,policies,expenses)}</div>`;
}
